image: node:14.0.0

stages:
  - test
  - build
  - deploy

before_script:
  - yarn install

test:
  stage: test
  cache:
    paths:
    - node_modules/
  script:
    - yarn test

build:
  stage: build
  cache:
    paths:
    - node_modules/

  script:
  - yarn build


deploy:
  stage: deploy
  image: ruby:latest
  cache:
    paths:
    - node_modules/

  script:
  - apt-get update -qy
  - apt-get install rubygems ruby-dev -y
  - gem install dpl
  - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY

