image: node:latest

stages:
  # - test
  # - build
  - deploy

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

# test:
#   stage: test
#   cache:
#     paths:
#     - node_modules/
#   script:
#     - yarn test

# build:
#   stage: build
#   cache:
#     paths:
#     - node_modules/

#   script:
#   - yarn build


deploy:
  stage: deploy
  image: ruby:latest
  cache:
    paths:
    - node_modules/

  script:
  - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY

